config/routes.rb
Rails.application.routes.draw do

  # Legacy redirects for URLs that are commonly in use
  get '/headlines/best' => redirect('/')
  get '/best(/today)' => redirect('/')

  devise_for :users, controllers: { registrations: "registrations" }

  resources :comments

  resources :headlines, except: [:show, :update, :edit, :destroy] do
    resources :comments
    collection do
      get :random
      get :download
    end
    member do
      post :vote
      get :reconstruct
      get :pick_photo
      get :tweet_from_bot
      post :update_photo
    end
  end

  resources :source_headlines do
    collection do
      get :download
    end
  end

  resources :sources

  resources :users do
    resources :headlines
    resources :votes
    resources :comments
  end

  get 'paper', to: "headlines#newspaper"

  get "leaderboard(/:timeframe)", to: "users#index", as: :leaderboard

  get "trending", to: "headlines#index", order: :trending, user_id: nil
  get "hot", to: "headlines#index", order: :hot, user_id: nil
  get "recent", to: "headlines#index", order: :new, user_id: nil

  get "generator", to: "generator#index"
  post "generator/save", to: "generator#save", as: :save

  get 'best/:timeframe', to: 'headlines#index'

  resources :headlines, only: [:show, :destroy], path: "/"
  get '/headlines/:id' => redirect('/%{id}')

  root to: "headlines#index"

end

app/controllers/sources_controller.rb
class SourcesController < ApplicationController

  def show
    @source = HeadlineSource.find(params[:id])
    @headlines = default_pagination headlines_sorted_by_params @source.headlines.top
  end

  def index
    @source_groups = HeadlineSource.all.sort_by{|s| "#{s.fake?}#{s.name.downcase}" }.group_by{|s| s.fake? ? "Fake News Sites" : "Headline Sources" }
  end

end

app/helpers/sources_helper.rb
module SourcesHelper

  def read_link_data(source_headline)
    return nil unless source_headline && source_headline.source
    d = {
      id: source_headline.id,
      source: source_headline.source.id
    }
    d[:headline_id] = @headline.id if @headline
    d
  end

end

app/views/sources/_source_stats.html.haml
%strong= number_with_delimiter source.headlines.count
= 'smash'.pluralize(source.headlines.count)

%span.text-muted /

- sum = source.votes.sum(:value)
%strong= number_with_delimiter sum
= 'upvote'.pluralize(sum)

%span.text-muted /

- count = source.source_headlines.count
smashed from
%strong= number_with_delimiter count
real
= 'headline'.pluralize(count)

.pull-right.text-right
  - avg = sum.to_f / count.to_f
  %strong= number_with_delimiter avg.round(1)
  average votes

app/views/sources/index.html.haml
- @title = "Sources"
%h2 Sources
%hr/
- @source_groups.each do |group, sources|
  %h3{:class => ("text-danger" if group == "Fake News Sites")}
    = group
  - if group == "Fake News Sites"
    .alert.alert-danger
      These are not legitimate news sources.
  %table.table.table-striped#sources-table
    - sources.each do |source|
      %tr
        %td.image
          = source_image_tag source, true
        %td.name
          %h4= link_to source.name, source_url(source.id), class: ("text-danger" if group == "Fake News Sites")

app/views/sources/show.html.haml
- @title = "Source | #{@source.name}"

%h2
  = link_to "Sources", sources_url
  %span.text-muted /
  = @source.name
  = link_to generator_url(@source.id => 1), class: "btn btn-primary pull-right" do
    %i.fa.fa-gears
    Smash #{@source.name}

.stats{style: 'clear:both'}
  = render partial: 'sources/source_stats', locals: {source: @source}


- if @source.fake?
  %br/
  #fake-news-alert.alert.alert-danger
    .label.label-danger Fake News Site
    #{@source.name} is not a legitimate news source.
    = link_to "Details", @source.fake_source, class: "btn btn-danger btn-sm pull-right"

%hr/

%h3 Most Popular Smashes

.sort-tools
  .btn-group.source-picker
    = link_to "Best", params.merge({page: 1, order: :top}), class: default_button_toggle(:order, :top, true)
    = link_to "Recent", params.merge({page: 1, order: :new}), class: default_button_toggle(:order, :new)

- @headline_table_show_sources = true
= render partial: 'headlines/headlines_table', locals: {headlines: @headlines}