config/routes.rb
Rails.application.routes.draw do

  # Legacy redirects for URLs that are commonly in use
  get '/headlines/best' => redirect('/')
  get '/best(/today)' => redirect('/')

  devise_for :users, controllers: { registrations: "registrations" }

  resources :comments

  resources :headlines, except: [:show, :update, :edit, :destroy] do
    resources :comments
    collection do
      get :random
      get :download
    end
    member do
      post :vote
      get :reconstruct
      get :pick_photo
      get :tweet_from_bot
      post :update_photo
    end
  end

  resources :source_headlines do
    collection do
      get :download
    end
  end

  resources :sources

  resources :users do
    resources :headlines
    resources :votes
    resources :comments
  end

  get 'paper', to: "headlines#newspaper"

  get "leaderboard(/:timeframe)", to: "users#index", as: :leaderboard

  get "trending", to: "headlines#index", order: :trending, user_id: nil
  get "hot", to: "headlines#index", order: :hot, user_id: nil
  get "recent", to: "headlines#index", order: :new, user_id: nil

  get "generator", to: "generator#index"
  post "generator/save", to: "generator#save", as: :save

  get 'best/:timeframe', to: 'headlines#index'

  resources :headlines, only: [:show, :destroy], path: "/"
  get '/headlines/:id' => redirect('/%{id}')

  root to: "headlines#index"

end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :rememberable, :trackable

  validates_uniqueness_of    :login,     :case_sensitive => false, :allow_blank => true, :if => :login_changed?
  validates_presence_of   :password, :on=>:create
  validates_confirmation_of   :password, :on=>:create
  validates_length_of :password, :within => Devise.password_length, :allow_blank => true

  validates_format_of :login, with: /\A[a-z0-9_-]+\Z/i, on: :create

  has_many :votes, dependent: :destroy
  has_many :upvotes, -> { upvotes }, class_name: 'Vote'
  has_many :downvotes, -> { downvotes }, class_name: 'Vote'
  has_many :headlines, foreign_key: :creator_id, dependent: :nullify
  has_many :voted_headlines, through: :votes, source: :headline
  has_many :upvoted_headlines, through: :upvotes, source: :headline
  has_many :downvoted_headlines, through: :downvotes, source: :headline

  has_many :comments, dependent: :destroy

  scope :top, -> { order("karma desc") }

  before_save do
    calculate_karma!
  end

  before_create :generate_api_key

  def generate_api_key
    begin
      self.api_key = SecureRandom.hex
    end while self.class.exists?(api_key: api_key)
  end

  def self.with_karma_for_timeframe(timeframe = nil)
    aggregate = -> (func) {
      <<-sql
      (SELECT #{func}
           FROM headlines
           WHERE headlines.creator_id = users.id
           #{timeframe ? "AND (headlines.created_at > #{sanitize timeframe.ago})" : ''}
          )
      sql
    }

    timeframe_headline_count = aggregate.call("COUNT(*)")
    timeframe_vote_count = aggregate.call("SUM(vote_count)")
    timeframe_karma = "#{timeframe_vote_count} - #{timeframe_headline_count}"

    sql = <<-sql
    #{timeframe_headline_count} AS timeframe_headline_count,
    #{timeframe_vote_count} AS timeframe_vote_count,
    #{timeframe_karma} AS timeframe_karma
    sql

    User.select('*', sql).where("#{timeframe_karma} is not null").order('timeframe_karma desc')
  end

  def has_calculated_timeframe_karma?
    self.respond_to?(:timeframe_karma)
  end

  def admin?
    login == "wil"
  end

  def calculate_karma!
    self.saved_headlines_count = self.headlines.count
    self.karma = self.headlines.sum(:vote_count) - self.saved_headlines_count
    self.vote_count = voted_headlines_without_self.count
  end

  def upvote_headline!(headline)
    clear_votes!(headline)
    headline.votes.create(user: self, value: 1)
    headline.save!
    headline.creator.save! if headline.creator
    self.save!
  end

  def downvote_headline!(headline)
    clear_votes!(headline)
    headline.votes.create(user: self, value: -1)
    headline.save!
    headline.creator.save! if headline.creator
    self.save!
  end

  def clear_votes!(headline)
    clear_votes headline
    headline.save!
    headline.creator.save! if headline.creator
    self.save!
  end

  def clear_votes(headline)
    votes.where(headline: headline).delete_all
  end

  def to_param
    login
  end

  def voted_headlines_without_self
    voted_headlines.where("headlines.creator_id is null or headlines.creator_id != ?", id)
  end

  def vote_statuses(headlines)
    VoteStatusCollection.new(self, headlines)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    if params[:timeframe] == "this_month"
      @users = User.with_karma_for_timeframe(1.month).limit(25)
    elsif params[:timeframe] == "this_week"
      @users = User.with_karma_for_timeframe(1.week).limit(25)
    elsif params[:timeframe] == "today"
      @users = User.with_karma_for_timeframe(1.day).limit(25)
    else
      @users = User.all.top.paginate(:page => params[:page], :per_page => 25)
    end
  end

  def show
    @user = User.find_by_login(params[:id])
    raise ActionController::RoutingError.new('Not Found') unless @user
  end

end

app/helpers/users_helper.rb
module UsersHelper

  def user_data
    return {} unless current_user.present?
    {
      username: current_user.login,
      created: current_user.created_at,
      karma: current_user.karma,
      comments: current_user.comments_count,
      saved: current_user.saved_headlines_count,
      votes: current_user.vote_count,
      signed_in: current_user.current_sign_in_at,
      newly_registered: flash[:newly_registered] ? 'true' : nil
    }
  end

end

app/views/users/_user.html.haml
%tr{class: "user-#{user.id} lead"}
  %td
    %strong ##{user_counter + 1 + (((params[:page] || 1).to_i - 1) * @users.per_page)}
  %td.login
    = link_to user.login, user
  %td.karma.text-left
    %i.fa.fa-trophy
    = number_with_delimiter user.has_calculated_timeframe_karma? ? user.timeframe_karma : user.karma
    karma
    .more-info.hidden-xs
      %span.text-muted
        = link_to pluralize(number_with_delimiter(user.has_calculated_timeframe_karma? ? user.timeframe_headline_count : user.saved_headlines_count), 'headline'), user_headlines_url(user)
        \/
        - if user.has_calculated_timeframe_karma?
          = link_to 'view votes', user_votes_url(user)
        - else
          = link_to pluralize(number_with_delimiter(user.vote_count), 'vote'), user_votes_url(user)
        \/
        - if user.has_calculated_timeframe_karma?
          = link_to 'view comments', user_comments_url(user)
        - else
          = link_to pluralize(number_with_delimiter(user.comments_count), 'comment'), user_comments_url(user)

app/views/users/index.html.haml
- @title = "Leaderboard"
- @short_title = :leaderboard

%h2 Leaderboard
.lead.text-muted Get karma when other people upvote your saved headlines.

.btn-group.source-picker
  = link_to "All Time", merge_sort_url({page: 1, timeframe: :all}), class: default_button_toggle(:timeframe, :all, true)
  = link_to merge_sort_url({page: 1, timeframe: :this_month}), class: default_button_toggle(:timeframe, :this_month) do
    %span.hidden-xs This
    Month
  = link_to merge_sort_url({page: 1, timeframe: :this_week}), class: default_button_toggle(:timeframe, :this_week) do
    %span.hidden-xs This
    Week
  = link_to merge_sort_url({page: 1, timeframe: :today}), class: default_button_toggle(:timeframe, :today) do
    Today

= cache cache_key_for_duration(10.minutes, ["leaderboard", params]) do
  %table.table.table-striped.users-table
    = render @users

= will_paginate @users, renderer: BootstrapPagination::Rails if @users.respond_to?(:total_pages)

%p
  %small.text-muted
    %i.fa.fa-refresh
    Leaderboard updates every 10 minutes.

app/views/users/show.html.haml
- @title = "User | #{@user.login}"

%h2
  = @user.login
  - if current_user == @user
    = link_to edit_user_registration_url, class: 'btn btn-default pull-right' do
      %i.fa.fa-edit
      Edit Profile

.lead
  .karma
    %i.fa.fa-trophy
    = @user.karma
    karma
    .pull-right.text-muted
      signed up #{timeago_tag @user.created_at}
  .karma
    %span.text-muted
      = link_to pluralize(@user.saved_headlines_count, 'saved headline'), user_headlines_url(@user)
  .karma
    %span.text-muted
      = link_to pluralize(@user.vote_count, 'vote'), user_votes_url(@user)
  .karma
    %span.text-muted
      = link_to pluralize(@user.comments_count, 'comment'), user_comments_url(@user)

- if @user == current_user
  %hr/
  .text-muted
    %small
      %strong API Key:
      = current_user.api_key
      .pull-right
        %strong API Requests:
        = number_with_delimiter current_user.api_requests