config/routes.rb
Rails.application.routes.draw do

  # Legacy redirects for URLs that are commonly in use
  get '/headlines/best' => redirect('/')
  get '/best(/today)' => redirect('/')

  devise_for :users, controllers: { registrations: "registrations" }

  resources :comments

  resources :headlines, except: [:show, :update, :edit, :destroy] do
    resources :comments
    collection do
      get :random
      get :download
    end
    member do
      post :vote
      get :reconstruct
      get :pick_photo
      get :tweet_from_bot
      post :update_photo
    end
  end

  resources :source_headlines do
    collection do
      get :download
    end
  end

  resources :sources

  resources :users do
    resources :headlines
    resources :votes
    resources :comments
  end

  get 'paper', to: "headlines#newspaper"

  get "leaderboard(/:timeframe)", to: "users#index", as: :leaderboard

  get "trending", to: "headlines#index", order: :trending, user_id: nil
  get "hot", to: "headlines#index", order: :hot, user_id: nil
  get "recent", to: "headlines#index", order: :new, user_id: nil

  get "generator", to: "generator#index"
  post "generator/save", to: "generator#save", as: :save

  get 'best/:timeframe', to: 'headlines#index'

  resources :headlines, only: [:show, :destroy], path: "/"
  get '/headlines/:id' => redirect('/%{id}')

  root to: "headlines#index"

end

app/models/headline.rb
require 'digest/sha1'

class Headline < ActiveRecord::Base
  include HeadlinePhotoConcern
  include AppropriatenessConcern
  include RandomConcern
  include Rails.application.routes.url_helpers

  scope :top, -> { order("headlines.score desc, headlines.created_at desc") }
  scope :bottom, -> { order("headlines.score asc, headlines.created_at desc") }
  scope :hot, -> { order("(headlines.vote_count / (extract(epoch from now()) - extract(epoch from headlines.created_at))) desc").where("headlines.created_at < ?", 20.minutes.ago).where("headlines.vote_count > 1 AND headlines.vote_count < 50") }
  scope :trending, -> { order("(COALESCE(headlines.retweet_count, 0) + headlines.mention_count + COALESCE(headlines.favorite_count, 0)) desc, headlines.updated_at desc") }
  scope :created_in_the_past, -> (timeframe){ where("headlines.created_at > ?", timeframe.ago) }
  scope :today, -> { created_in_the_past 1.day }
  scope :this_week, -> { created_in_the_past 7.days }
  scope :this_month, -> { created_in_the_past 30.days }
  scope :this_year, -> { created_in_the_past 1.year }
  scope :yesterday, -> { where("headlines.created_at > ? AND headlines.created_at < ?", 2.days.ago, 1.day.ago) }
  scope :newest, -> { order("headlines.created_at desc") }
  scope :babies, -> { where(vote_count: 1) }
  scope :just_in, -> { this_month.babies.order("random()") }

  scope :no_metadata, -> { includes(:source_headline_fragments).where(source_headline_fragments: {headline_id: nil}) }

  scope :tweeted, -> { where("bot_shared_at is not null") }
  scope :scorable, -> { where("comments_count > 0 OR retweet_count > 0 OR favorite_count > 0 OR mention_count > 0") }
  scope :tweetable, -> { where({bot_shared_at: nil}).appropriate }
  scope :retweetable, -> { appropriate.where.not({bot_shared_at: nil}) }

  scope :with_name,  -> (name){ where(name_hash: Headline.name_hash(name)) }
  scope :minimum_score, -> (score){ where("score >= ?", score) }

  validates_presence_of :name
  validates_uniqueness_of :name_hash

  has_many :votes, dependent: :destroy
  has_many :comments, dependent: :destroy
  belongs_to :creator, class_name: "User"

  has_many :source_headline_fragments, dependent: :destroy
  has_many :source_headlines, through: :source_headline_fragments

  has_many :headline_twitter_mentions

  serialize :source_names, Array
  serialize :photo_data, Hash

  before_validation do
    self.name_hash = Headline.name_hash(self.name)
    calculate_vote_count!
    calculate_score!
  end

  # after_create do
  #   find_photo! if needs_photo_load?
  # end

  def calculate_vote_count!
    self.vote_count = self.votes.upvotes.sum(:value)
  end

  def calculate_score!
    new_score = vote_count.to_f
    # Unique commenters who are not the creator
    new_score += comments.map{|c| c.user.id}.reject{|i| i == self.creator_id }.uniq.length.to_f
    new_score += retweet_count.to_f * 3
    new_score += favorite_count.to_f * 2
    new_score += if tweeted_from_bot?
      mention_count.to_f * 2
    else
      mention_count.to_f * 4
    end
    self.score = new_score
  end

  def display_score
    score.floor
  end

  def self.name_hash(name)
    name.parameterize
  end

  # def to_param
  #   "#{id}-#{name.parameterize}"
  # end

  def categories
    # What am I doing it's so late.
    cats = {}
    source_objects.each do |source|
      if cats[source.category].present?
        cats[source.category] = cats[source.category] + 1
      else
        cats[source.category] = 1
      end
    end
    sorted = cats.to_a.sort{|c| c[1] }
    sorted = sorted[0,2] if sorted.length > 2
    sorted.map{|pair| pair[0]}
  end

  def self.salted_hash(headline)
    Digest::SHA1.hexdigest("#{headline}-#{ENV['HEADLINE_INJECTION_SALT']}")
  end

  def salted_hash
    Headline.salted_hash(name)
  end

  def downvote_count
    @downvote_count ||= votes.downvotes.sum(:value).abs
  end

  def upvote_count
    @upvote_count ||= votes.upvotes.sum(:value)
  end

  def set_source_names
    names = source_headlines.map(&:source_id)
    self.source_names = names if names.present?
  end

  def sources
    source_headlines.map(&:source).compact.uniq{|source| source.id}
  end

  def create_sources!(sources_json_array)
    SourceHeadlineFragment.transaction do
      sources_json_array.each_with_index do |source_hash, i|

        source_headline = SourceHeadline.find(source_hash['source_headline_id'])

        fragment = SourceHeadlineFragment.new
        fragment.headline = self
        fragment.source_headline = source_headline
        fragment.source_headline_start = source_headline.name.downcase.index(source_hash['fragment'].downcase)
        fragment.source_headline_end = fragment.source_headline_start + source_hash['fragment'].length
        fragment.index = i
        fragment.save!

      end
    end
    set_source_names
  end

  def shitty?
    vote_count < 1
  end

  def self.last_tweet_time
    Headline.where("bot_shared_at is not null").order("bot_shared_at desc").first.try(:bot_shared_at)
  end

  def self.last_retweet_time
    Headline.where("retweeted_at is not null").order("retweeted_at desc").first.try(:retweeted_at)
  end

  def tweeted_from_bot?
    bot_shared_at.present?
  end

  def bot_tweet_url
    "https://twitter.com/headlinesmasher/status/#{bot_share_tweet_id}"
  end

  def self.normalize_smart_quotes(string)
    string.gsub("’", "'").gsub("‘", "'").gsub('“', '"').gsub('”', '"')
  end

  # Must be the same length as original headline
  def repunctuated_name

    out = Headline.normalize_smart_quotes(name)

    # Weird characters
    out.gsub!("Â", " ")
    out.gsub!("\u0091", "'")
    out.gsub!("\u0092", "'")
    out.gsub!("\u0093", "\"")
    out.gsub!("\u0094", "\"")

    if out.count('"') == 1 && !out.match(/\d{1,2}'\d{1,2}"/)
      out = out.sub('"', ' ')
    end

    # Replace single quoted things with double quotes
    matches = out.match(/((?:\A| )'[\w\s]+'(?:\z| ))/)
    if matches
      matches.length.times do |i|
        start_i, end_i = matches.offset(i)
        pre = out[0, start_i]
        mid = out[start_i, end_i - start_i]
        post = out[end_i, out.length]
        out = pre + mid.gsub("'", "\"") + post
      end
    end

    # Replace mismatched single quotes that aren't contractions
    out.gsub!(/'([^a-zA-Z0-9_+])/, ' \1')
    out.gsub!(/([^a-zA-Z0-9_+])'/, '\1 ')
    out.gsub!(/([a-zA-Z0-9_+])'\z/, '\1 ')
    out.gsub!(/\A'([a-zA-Z0-9_+])/, ' \1')

    %w[: ? ! ;].each do |punctuation|
      out.gsub!(" #{punctuation} ", "#{punctuation}  ")
    end

    # Don't quote entire headlines
    if out.count('"') == 2 && out.start_with?('"') && out.end_with?('"')
      out.gsub!('"', ' ')
    end

    terminators = %w[. , : ;]
    terminators << ")" if out.count("(") == 0 && out.count(")") == 1
    terminators.each do |terminator|
      if out.end_with?(terminator) && !out.end_with?("...")
        out = out.chop + " "
      end
      if out.count(terminator) == 1 && out.strip.end_with?(terminator)
        out = out.sub(terminator, ' ')
      end
    end

    # Mismatched double quotes
    open_quotes = out.scan(/[ -]"/).length
    close_quotes = out.scan(/[ -]"/).length
    if open_quotes > close_quotes
      out = out.reverse.sub("\" ", "  ").reverse
    end
    if open_quotes < close_quotes
      out = out.sub("\" ", "  ")
    end

    out
  end

  def formatted_name
    @_formatted_name ||= repunctuated_name.squish
  end

  def tweet_from_bot!
    tweet = TWITTER_BOT_CLIENT.update(formatted_name)
    self.bot_shared_at = Time.now
    self.bot_share_tweet_id = tweet.id
    self.save!
  end

  def retweet_from_bot!
    rt = TWITTER_BOT_CLIENT.retweet(bot_share_tweet_id)
    self.retweeted_at = Time.now
    self.save!
  end

  def self.high_quality_randomized(scope:)
    # A batch of the top headlines that:
    #   - at least someone else thought was funny
    #   - are the best scoring
    good_ones = scope.top.minimum_score(2)

    # We'll pick a random timeframe, so that we guarantee we will
    # eventually cover the whoe scope, but prefer more recent stuff so
    # that we don't just cover old news.
    timeframe_scopes = {today: 5, this_week: 10, this_month: 20, this_year: 50, all: 200}

    # Get the top ones from the timeframe
    # (if there are none try all the rest of the timeframes)
    batch = []
    timeframe_scopes.to_a.shuffle.each do |(timeframe, limit)|
      batch = good_ones.send(timeframe).limit(limit).to_a
      break unless batch.empty?
    end

    # There must just be no matching headlines
    return nil if batch.empty?

    # Pick a random headline from the batch
    batch.sample
  end

  def self.high_quality_tweetable
    high_quality_randomized(scope: tweetable)
  end

  def self.high_quality_retweetable(timeframe: 6.months)
      retweetable
        .where(["retweeted_at is null OR retweeted_at < ?", timeframe.ago])
        .order('random()')
        .first
  end

end

app/controllers/headlines_controller.rb
class HeadlinesController < ApplicationController

  before_filter :protect_api, only: [:random, :show]

  layout false, only: :newspaper

  def index
    if params[:user_id]
      @user = User.find_by_login!(params[:user_id])
      @headlines = headlines_sorted_by_params @user.headlines
    else
      @is_main_browse_page = true
      @headlines = headlines_sorted_by_params Headline.all, {order: :top, timeframe: :this_week, q: nil}
    end
    @headlines = default_pagination @headlines
  end

  def show
    @headline = Headline.includes(:source_headline_fragments, :source_headlines, :comments).find(params[:id])
    respond_to do |format|
      format.html
      format.js
      format.json {render partial: "headlines/headline", locals: {headline: @headline}}
    end
  end

  def random
    @headline = Headline.minimum_score(params[:minimum] || 2).order('random()').first
    respond_to do |format|
      format.html { redirect_to @headline }
      format.json {render partial: "headlines/headline", locals: {headline: @headline}}
    end
  end

  def newspaper
    @headlines = Headline.minimum_score(params[:minimum] || 10).order('random()').limit(19).to_a
  end

  def download
    if current_user && current_user.admin?
      limit = params[:limit].to_i.zero? ? 1000 : params[:limit].to_i
      collection = if params[:percent]
        Headline.random_set(percent: params[:percent].to_f).pluck(:name)
      else
        Headline.random_set(approximate_limit: limit).pluck(:name)
      end
      headers['Content-Disposition'] = "attachment" if params[:download]
      respond_to do |format|
        format.json { render json: collection }
        format.text { render text: collection.join("\n") }
      end
    else
      head :not_found
    end
  end

  def reconstruct
    @headline = Headline.find(params[:id])
    redirect_to generator_url(reconstruct_phrase: @headline.name, reconstruct_sources: @headline.source_names.join(","))
  end

  def tweet_from_bot
    raise unless current_user.login == 'wil'
    @headline = Headline.find(params[:id])
    @headline.tweet_from_bot!
    redirect_to @headline.bot_tweet_url
  end

  def pick_photo
    @headline = Headline.find(params[:id])
    @search = params[:search].presence || @headline.tags.join(", ")
    @photos = flickr.photos.search(tags: @search, per_page: 50, sort: 'relevance', media: 'photos', extras: "owner_name,license")
  end

  def update_photo
    @headline = Headline.find(params[:id])
    @headline.set_photo! JSON.parse(params[:json])
    redirect_to @headline
  end

  def vote
    head :ok and return if VOTING_DISABLED
    @headline = Headline.find(params[:id])
    # Headline.transaction do
      if params[:down].to_i == 1
        if did_downvote?(@headline)
          current_user.clear_votes! @headline
        else
          current_user.downvote_headline! @headline
        end
      else
        if did_upvote?(@headline)
          current_user.clear_votes! @headline
        else
          current_user.upvote_headline! @headline
        end
      end
    # end
    @headline.reload
  end

  def destroy
    @headline = Headline.find(params[:id])
    @headline.destroy! if @headline.vote_count < 2 && @headline.creator == current_user
    respond_to do |format|
      format.html {redirect_to root_path}
      format.js
    end
  end

end

app/helpers/headlines_helper.rb
module HeadlinesHelper

  def headlines_sorted_by_params(headlines, defaults = {order: :top, timeframe: :all, q: nil})
    # Get the params from the request and merge them with the defaults
    sort_order     = (params[:order].presence || defaults[:order]).to_sym
    sort_timeframe = (params[:timeframe].presence || defaults[:timeframe]).to_sym
    query          = params[:q].presence || defaults[:q].presence

    if sort_order == :new
      headlines = headlines.newest
    elsif sort_order == :trending
      headlines = headlines.trending
    elsif sort_order == :hot
      headlines = headlines.hot
    elsif sort_order == :top
      @sorting_top = true
      headlines = headlines.top
      if sort_timeframe == :all
      elsif sort_timeframe == :yesterday
        headlines = headlines.yesterday
      elsif sort_timeframe == :day
        headlines = headlines.today
      elsif sort_timeframe == :this_week
        headlines = headlines.this_week
      elsif sort_timeframe == :this_month
        headlines = headlines.this_month
      elsif sort_timeframe == :today
        headlines = headlines.today
      end
    end

    if query
      headlines = headlines.where("headlines.name ilike (?)", "%#{query}%")
    end

    headlines
  end

  def merge_sort_url(new_params)
    merged = params.merge(new_params)
    merged.delete(:page) if params[:page].blank? || merged[:page].to_i == 1
    merged
  end

  def default_pagination(scope)
    scope.paginate(:page => params[:page], :per_page => 40)
  end

  def tooltipped_headline(headline, options = {})
    options = {inner_linked: false}.merge(options)
    if headline.source_headline_fragments.length > 0 && headline.source_headline_fragments.all?{|shf| shf.source_headline.present? }
      render partial: 'headlines/tooltips/outer', locals: {headline: headline, options: options}
    else
      headline.name
    end
  end

  def selected_sources_includes?(source)
    @sources.present? && @sources.include?(source.id)
  end

  def source_image_url(source)
    return nil unless source && source.has_icon?
    image_url("headline_sources/#{source.id}.png")
  end

  def source_image_tag(source, linked = false)
    return nil unless source && source.has_icon?
    img = image_tag(source_image_url(source), class: 'source-icon', alt: source.name)
    if linked
      link_to img, source_url(source.id), data: {toggle: :tooltip, title: source.name}, class: 'source-icon-link'
    else
      img
    end
  end

  def active_if_param(param_name, param_value, also_if_blank = false)
    params[param_name].to_s == param_value.to_s || also_if_blank && params[param_name].blank? ? 'active' : ''
  end

  def default_button_toggle(*args)
    "btn btn-default " + active_if_param(*args)
  end

  def main_button_best_toggle(value, button_class, also_if_blank = false)
    k = "btn #{button_class} btn-default "
    k << active_if_param(:order, value, also_if_blank) if @is_main_browse_page
    k
  end

  def main_button_explore_class(button_class)
    k = "btn #{button_class} btn-default "
    if @is_main_browse_page
      k << active_if_param(:order, :top, true) + " "
      k << active_if_param(:order, :trending) + " "
      k << active_if_param(:order, :new) + " "
    end
    k
  end

  def tweet_url(headline)
    "https://twitter.com/intent/tweet?text=#{CGI.escape headline.formatted_name}&source=#{CGI.escape "Headline Smasher"}&url=#{headline_url(headline)}&related=HeadlineSmasher"
  end

  def facebook_share_url(headline)
    "https://www.facebook.com/sharer/sharer.php?u=#{headline_url(headline)}"
  end

  def headline_description(headline)
    d = "#{pluralize headline.display_score, "vote"}"
    if headline.creator
      d << ", discovered by #{headline.creator.login}"
    end
    d
  end

  def loading_icon
    "..."
  end

end

app/views/headlines/_headline_downvotebox.html.haml
= link_to vote_headline_url(headline, down: 1), remote: true, method: :post, class: "btn #{vote_statuses.did_downvote?(headline) ? "btn-danger" : 'btn-default'} downvote-button", data: {disable_with: loading_icon} do
  %i.fa.fa-thumbs-down

app/views/headlines/_headline_votebox.html.haml
- if user_signed_in?
  = link_to vote_headline_url(headline, keybind: defined?(keybind) && keybind), remote: true, method: :post, class: "btn #{vote_statuses.did_upvote?(headline) ? "btn-success" : 'btn-default'} upvote-button", data: {disable_with: loading_icon, keybinding: defined?(keybind) && keybind ? 'v' : nil} do
    %i.fa.fa-thumbs-up
    - unless can_downvote?(headline) || vote_statuses.did_downvote?(headline)
      - if vote_statuses.did_upvote?(headline)
        Voted
      - else
        Vote
- else
  %buton.btn.btn-default.upvote-button{data:{toggle: 'modal', target: '#modal-login-form'}}
    %i.fa.fa-thumbs-up
    Vote

app/views/headlines/_headlines_table.html.haml
- breaking = defined?(breaking) && breaking
- if !headlines || headlines.length < 1
  .well
    No headlines found.
- else
  - vote_statuses = current_user.present? ? current_user.vote_statuses(headlines) : VoteStatusCollection.new
  %table.table.table-striped.headlines-table
    - headlines.each do |h|
      = render partial: 'headlines/headline', locals: {headline: h, vote_statuses: vote_statuses, breaking: breaking}
  - if headlines.respond_to?(:total_pages) && !(defined?(no_paginate) && no_paginate)
    = will_paginate headlines, renderer: BootstrapPagination::Rails

app/views/headlines/_sort_tools.html.haml
.sort-tools

  .btn-group.source-picker
    = link_to root_path, class: main_button_best_toggle(:top, "", true) do
      %i.fa.fa-star
      Top
    = link_to hot_url, class: main_button_best_toggle(:hot, "") do
      %i.fa.fa-flash
      Hot
    = link_to recent_url, class: main_button_best_toggle(:new, "") do
      %i.fa.fa-clock-o
      New

  - if @sorting_top
    .btn-group.source-picker.source-picker-timeframes.pull-right
      = link_to merge_sort_url({page: 1, timeframe: :this_week}), class: default_button_toggle(:timeframe, :this_week, true) do
        Week
      = link_to merge_sort_url({page: 1, timeframe: :this_month}), class: default_button_toggle(:timeframe, :this_month) do
        Month
      = link_to "All Time", merge_sort_url({page: 1, timeframe: :all}), class: default_button_toggle(:timeframe, :all)

  = form_tag params, class: 'searchbar', method: :get do
    %span.input-group
      %span.input-group-addon
        %i.fa.fa-search
      = hidden_field_tag :timeframe, params[:timeframe].presence || :all
      = text_field_tag :q, params[:q], placeholder: "Search", class: "form-control"
      - if params[:q].present?
        %span.input-group-btn
          = link_to merge_sort_url(q: nil), class: "btn btn-default input" do
            %i.fa.fa-times

app/views/headlines/destroy.js.erb
$(".generated-headline-<%= @headline.salted_hash %>").remove();

app/views/headlines/edit.html.haml
- @title = "Edit Headline | #{@headline.name}"

%h2
  Edit Punctuation &amp; Capitalization
%h4.text-muted= @headline.name
%br/

- @headline.errors.full_messages.each do |msg|
  .alert.alert-danger= msg

= form_for @headline, class: 'form-horizontal' do |f|
  .form-group
    = f.text_area :name, class: 'form-control'

  .form-group
    = f.submit "Update Punctuation & Capitalization", class: 'btn btn-primary'
    = link_to "Cancel", @headline, class: 'btn btn-default'

app/views/headlines/generator.html.haml
- @title = "Generator"
- @short_title = :generator

.row
  .col-md-4
    .generate-form
      = form_tag generate_headlines_path, method: :post, data: {remote: true} do
        = submit_tag "Generate Hilarious Headlines", class: "btn btn-warning btn-lg", disable_with: "Generating...", id: "invent-button"
        .source-box
          - Source.categories.each do |category_name, sources|
            .source-category
              %strong #{category_name}
              %br/
              - sources.each do |source|
                %span.source-checkbox-block
                  = check_box_tag source.id, 1, selected_sources_includes?(source)
                  = label_tag source.id do
                    = source_image_tag source
                    = source.name
  .col-md-8
    %p.text-muted
      Computers are good at smashing headlines together, but only you can help us discover which are the silliest.
    %p.text-muted
      If you find a good one, save it to #{link_to "the list of best headlines", best_url}.

    #generated-headlines

:javascript
  $(function(){
    $("#invent-button").click();
  });

app/views/headlines/pick_photo.html.haml
%h1 Pick Photo
%h4= link_to @headline.formatted_name, @headline
- @title = "Pick Photo"

%hr

= form_tag url_for, {method: :get} do
  .input-group
    = text_field_tag  :search, @search, class: "form-control"
    .input-group-btn
      = submit_tag "Search", class: "btn btn-primary"

%hr

- @photos.to_a.in_groups_of(4, false) do |photos|
  .row
    - photos.each do |photo|
      .col-md-3
        = form_tag update_photo_headline_url(@headline) do |f|
          = hidden_field_tag :json, photo.to_json
          = image_submit_tag FlickRaw.url_m(photo), style: "width:100%;height:auto;"

app/views/headlines/show.html.haml
- @title = @headline.formatted_name
- og! "og:title", @headline.formatted_name
- og! "og:image", @headline.image_url('n', false)
- og! "og:url", headline_url(@headline)
- og! "og:description", headline_description(@headline)

- og! "twitter:card", "summary"
- og! "twitter:site", "@HeadlineSmasher"
- og! "twitter:title", @headline.formatted_name
- og! "twitter:description", headline_description(@headline)

#headline-show{class: @headline.has_photo? ? "has-photo" : "no-photo"}
  %div{class: @headline.has_photo? ? "" : "col-md-10 col-md-offset-1"}
    .main-column{class: @headline.has_photo? ? "" : "row"}
      %h1= tooltipped_headline @headline, inner_linked: true
  .row
    - if @headline.has_photo?
      .photo-column.col-md-3
        = link_to @headline.image_info_url do
          = image_tag @headline.image_url('z'), alt: @headline.formatted_name, class: "headline-image"
        %small.text-muted.photo-credit
          - if @headline.image_owner.present?
            by #{link_to @headline.image_owner, @headline.image_info_url}
          via #{link_to "Flickr", @headline.image_info_url}
    .main-column{class: @headline.has_photo? ? "col-md-9" : "col-md-10 col-md-offset-1"}
      %h2
        .count.text-muted
          %span#show-vote-count= pluralize @headline.display_score, "vote"
          - unless VOTING_DISABLED
            #show-vote-box.votebox.pull-left= render partial: "headlines/headline_votebox", locals: {keybind: true, headline: @headline, vote_statuses: VoteStatusCollection.new(current_user, [@headline])}
          #headline-show-social.pull-right
            .btn-toolbar
              .btn-group
                = link_to(tweet_url(@headline), abbr: "Tweet", target: "_blank", class: 'btn btn-primary social-share-link twitter-share-link', data: {headline_id: @headline.id}) do
                  %i.fa.fa-twitter
                  Tweet
              .btn-group
                = link_to(facebook_share_url(@headline), abbr: "Share on Facebook", target: "_blank", class: 'btn btn-primary social-share-link facebook-share-link', data: {headline_id: @headline.id}) do
                  %i.fa.fa-facebook-square
                  Share

    %div{class: @headline.has_photo? ? "col-md-9" : "col-md-10 col-md-offset-1"}
      .row
        .col-md-6
          #headline-comments
            = render partial: 'comments/comments', locals: {headline: @headline}
        .col-md-6
          - if @headline.creator
            .well
              %h4.text-muted{style: 'margin:0'}
                discovered by #{link_to @headline.creator.login, @headline.creator}
                .pull-right.hidden-md #{timeago_tag @headline.created_at}
              .visible-md
                .text-muted #{timeago_tag @headline.created_at}

          - if @headline.source_headlines.length > 0
            .well
              %h4.text-muted{style: 'margin-top:0'}
                Smashed From These Stories
              %ul#show-headline-source-headline-list.list-unstyled
                - @headline.source_headlines.each do |source_headline|
                  %li
                    .pull-right
                      .btn-toolbar
                        .btn-group
                          = link_to source_headline.article_url, class: "btn read-article-link btn-success btn-xs", data: read_link_data(source_headline) do
                            %i.fa.fa-globe
                            Read
                        .btn-group
                          = link_to source_headline, class: "btn btn-default btn-xs" do
                            %i.fa.fa-gear
                            Smashes
                    .source-headline
                      = link_to source_headline.name, source_headline.article_url, class: 'read-article-link', data: read_link_data(source_headline)
                    - if source_headline.source
                      .source
                        = link_to source_url(source_headline.source.id) do
                          - if source_headline.source.fake?
                            .label.label-danger Fake News Site
                          = source_image_tag source_headline.source
                          = source_headline.source.name

          %small.text-muted
            - if @headline.sources
              %p
                = link_to generate_url_like(@headline) do
                  %i.fa.fa-gears
                  Smash from these news sources
            - if current_user.present? && current_user.admin?
              %p
                Score
                %strong #{@headline.score || "?"}
                Vote Count
                %strong #{@headline.vote_count || "?"}
                Retweets
                %strong #{@headline.retweet_count || "?"}
                Favorites
                %strong #{@headline.favorite_count || "?"}
                Mentions
                %strong #{@headline.mention_count || "?"}
              - if @headline.source_headlines.length == 0
                = link_to "Find Sources", reconstruct_headline_url(@headline)
              - if @headline.tweeted_from_bot?
                %p
                  = link_to @headline.bot_tweet_url do
                    %i.fa.fa-twitter
                    Auto-Tweeted on #{@headline.bot_shared_at.strftime("%A, %B %e, %Y")}
              %p
                = link_to pick_photo_headline_url(@headline) do
                  %i.fa.fa-camera
                  Pick Photo
                %span.text-muted
                  (
                  - @headline.tags.each do |tag|
                    = link_to tag, pick_photo_headline_url(@headline, search: tag), class: "text-muted"
                  )

            - if @headline.vote_count < 2 && @headline.creator == current_user
              .pull-right= link_to "Delete Headline", @headline, method: :delete, confirm: "Are you sure you want to delete this headline?", class: 'text-muted'