config/routes.rb
Rails.application.routes.draw do

  # Legacy redirects for URLs that are commonly in use
  get '/headlines/best' => redirect('/')
  get '/best(/today)' => redirect('/')

  devise_for :users, controllers: { registrations: "registrations" }

  resources :comments

  resources :headlines, except: [:show, :update, :edit, :destroy] do
    resources :comments
    collection do
      get :random
      get :download
    end
    member do
      post :vote
      get :reconstruct
      get :pick_photo
      get :tweet_from_bot
      post :update_photo
    end
  end

  resources :source_headlines do
    collection do
      get :download
    end
  end

  resources :sources

  resources :users do
    resources :headlines
    resources :votes
    resources :comments
  end

  get 'paper', to: "headlines#newspaper"

  get "leaderboard(/:timeframe)", to: "users#index", as: :leaderboard

  get "trending", to: "headlines#index", order: :trending, user_id: nil
  get "hot", to: "headlines#index", order: :hot, user_id: nil
  get "recent", to: "headlines#index", order: :new, user_id: nil

  get "generator", to: "generator#index"
  post "generator/save", to: "generator#save", as: :save

  get 'best/:timeframe', to: 'headlines#index'

  resources :headlines, only: [:show, :destroy], path: "/"
  get '/headlines/:id' => redirect('/%{id}')

  root to: "headlines#index"

end

app/views/layouts/_analytics.html.haml
:javascript
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', '#{ ENV['GOOGLE_ANALYTICS_ID'] }', '#{ ENV['GOOGLE_ANALYTICS_URL'] }');
  ga('require', 'linkid', 'linkid.js');
  ga('require', 'displayfeatures');
  ga('send', 'pageview');
:javascript
  (function(e,b){if(!b.__SV){var a,f,i,g;window.mixpanel=b;a=e.createElement("script");a.type="text/javascript";a.async=!0;a.src=("https:"===e.location.protocol?"https:":"http:")+'//cdn.mxpnl.com/libs/mixpanel-2.2.min.js';f=e.getElementsByTagName("script")[0];f.parentNode.insertBefore(a,f);b._i=[];b.init=function(a,e,d){function f(b,h){var a=h.split(".");2==a.length&&(b=b[a[0]],h=a[1]);b[h]=function(){b.push([h].concat(Array.prototype.slice.call(arguments,0)))}}var c=b;"undefined"!==
  typeof d?c=b[d]=[]:d="mixpanel";c.people=c.people||[];c.toString=function(b){var a="mixpanel";"mixpanel"!==d&&(a+="."+d);b||(a+=" (stub)");return a};c.people.toString=function(){return c.toString(1)+".people (stub)"};i="disable track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config people.set people.set_once people.increment people.append people.track_charge people.clear_charges people.delete_user".split(" ");for(g=0;g<i.length;g++)f(c,i[g]);
  b._i.push([a,e,d])};b.__SV=1.2}})(document,window.mixpanel||[]);
  mixpanel.init("#{ ENV['MIXPANEL_API_KEY'] }");

app/views/layouts/_footer.html.haml
%footer
  .text-muted
    .row.text-center
      %p
        = link_to "https://twitter.com/HeadlineSmasher" do
          %i.fa.fa-twitter
          Follow
          %strong @HeadlineSmasher
          on Twitter
      .more Get the best smashes all up in your social business.
    %hr/
    .row
      .col-md-6
        %p
          Built by
          = link_to "http://www.wilgieseler.com/" do
            Wil Gieseler
          as a weird side project thing.
        %p Follow me on Twitter at #{link_to "@wilgieseler", "https://twitter.com/wilgieseler"} if that's your jam.
        = link_to random_headlines_url, class: 'btn btn-primary random-headline-link' do
          %i.fa.fa-refresh
          Random Smash
      .col-md-6.text-right
        %p
          = link_to "https://github.com/wilg/headlines/issues" do
            %i.fa.fa-lightbulb-o
            Make a Suggestion
        %p
          = link_to "https://github.com/wilg/headlines/issues" do
            %i.fa.fa-bug
            Report a Bug
        %p
          = link_to "https://github.com/wilg/headlines" do
            %i.fa.fa-code
            View Source or Contribute on GitHub
  %hr/
  %p
    .pull-right
      %small.text-muted
        Original headlines are copyrighted by their respective owners. This is a parody of news headlines.
    %small.text-muted
      &copy; #{Time.now.year} Wil Gieseler
  %br

app/views/layouts/_header.html.haml
%header
  .container
    #header-content
      .clearfix
        .pull-left.site-image
          = link_to root_path do
            = image_tag "logo.png"
        .pull-left.site-title-box
          %h1.site-title
            = link_to root_path do
              Headline
              %i.fa.fa-gavel
              Smasher
          .lead Real news remixed into fake news.
        .hidden-xs.pull-right= render 'layouts/login_box'

      - [["visible-xs", "btn-sm"], ["hidden-xs", "btn-lg"]].to_h.each do |toolbar_class, button_class|
        .btn-toolbar{class: toolbar_class}
          .btn-group
            = link_to root_path, class: main_button_explore_class(button_class) do
              %i.fa.fa-star
              Explore
            - unless GENERATOR_DISABLED
              = link_to generator_url, class: "btn #{button_class} btn-default #{@short_title == :generator ? "active" : "btn-default"}" do
                %i.fa.fa-gears
                Smash
          .btn-group.pull-right
            = link_to leaderboard_url, class: "btn #{button_class} btn-default #{@short_title == :leaderboard ? "active" : "btn-default"}" do
              %i.fa.fa-trophy
              Leaderboard
            = link_to random_headlines_url, class: "btn #{button_class} btn-default random-headline-link", data: { keybinding: 'r' } do
              %i.fa.fa-refresh
              Random

      .visible-xs.text-center= render 'layouts/login_box'

app/views/layouts/_login_apology.html.haml
#modal-login-form.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", role: "dialog", tabindex: "-1"}
  .modal-dialog
    .modal-content
      .modal-body
        .clearfix#sign-up-collapses
          #login-column-left
            #register-form.collapse.in
              %h3{style: "margin-top:0"} Sign Up
              %p
                %strong.text-success No personal information required.
              = form_for(User.new, :as => :user, :url => registration_path(:user), class: "form-horizontal") do |f|
                .form-group
                  = f.label :login, "Username"
                  = f.text_field :login, :autofocus => true, class: 'form-control'
                .form-group
                  = f.label :password
                  = f.password_field :password, class: 'form-control'
                .form-group
                  = f.label :password_confirmation
                  = f.password_field :password_confirmation, class: 'form-control'
                .form-group
                  = f.submit "Sign Up", class: 'btn btn-primary'
            #sign-in-form.collapse
              %h4 Existing users sign in
              = form_for(User.new(remember_me: true), :as => :user, :url => session_path(:user), class: "form-horizontal") do |f|
                = f.hidden_field :remember_me
                .form-group
                  = f.label :login, "Username"
                  = f.text_field :login, :autofocus => true, class: 'form-control'
                .form-group
                  = f.label :password
                  = f.password_field :password, class: 'form-control'
                .form-group
                  = f.submit "Sign In", class: 'btn btn-primary'
          #login-column-right
            %h4{style: "margin-top:0"} Why do I need an account? That is stupid and dumb!
            %p You don't need an account to use the generator or browse around, but if you make one you can:
            %ul
              %li
                %strong Save headlines
                from the generator
              %li
                %strong Vote
                on headlines
              %li
                Earn sweet, sweet
                %strong karma
            %p We tried to do it without accounts for a while, but a few people kept cheating and hacking and being rude.
            %p
              It's
              %strong completely free
              and we don't ask for any personal information so
              %strong we can't spam you.
            %hr/
            = link_to "I Already Have An Account", new_user_session_url, class: 'btn btn-default btn-block'

app/views/layouts/_login_box.html.haml
#login-box.text-muted
  %span.label.label-success.pull-right.new-feature
  - if user_signed_in?
    = link_to destroy_user_session_path, method: :delete, class: 'btn btn-link btn-autohide link-muted' do
      %i.fa.fa-sign-out
      %span sign out
    = link_to current_user, class: 'btn btn-link' do
      %i.fa.fa-user
      #{current_user.login} (#{number_with_delimiter current_user.karma})
  - else
    .btn.btn-default.btn-sm{data:{toggle: 'modal', target: '#modal-login-form'}}
      %i.fa.fa-user
      Sign Up
    = link_to new_user_session_url, class: 'btn btn-default btn-sm' do
      %i.fa.fa-sign-in
      Sign In

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Headline Smasher | #{@title}
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
    = favicon_link_tag 'favicon.ico'
    %meta{name: 'viewport', content: 'width=device-width, initial-scale=1.0'}
    %meta{name: 'apple-mobile-web-app-title', content: 'Smasher'}
    %link{rel: 'apple-touch-icon', href: image_url('apple-touch-icon.png') }
    %meta{charset: 'utf-8'}
    - og_tags.each do |k, v|
      %meta{property: k, content: v}
  %body{class: user_signed_in? ? 'logged-in' : 'logged-out', data: user_data}
    = render 'layouts/header'

    .container
      - if ENV['SITE_ALERT'].present?
        #site-alert.alert.alert-warning.text-center
          %strong Hey!
          = ENV['SITE_ALERT']

      %br/

      = yield

      %hr/

      = render 'layouts/footer'

    #upvoted-button{style: "display:none"}
      %button.btn.disabled{type: :button}
        %i.fa.fa-thumbs-up
        Voted
    = render 'layouts/login_apology'

  = render 'layouts/analytics'